# .github/workflows/activity.yml
name: Update README Activity
on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:
permissions: { contents: write }
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.4
        with:
          COMMIT_MSG: "chore: update activity"
          MAX_LINES: 6
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update activity"
